import Head from "next/head"
import Link from "next/link"
import cn from 'classnames'
import s from './index.module.less'
import { useEffect, useState } from "react"

const title = '每一天都记录，每一次记录都是进步'
export default function Header() {
    const menu = [
        { title: '笔记广场', path: '/' },
        { title: '我的笔记', path: '/personal' },
        { title: '帅气博主', path: '/owner' },
    ]
    const [active, setActive] = useState<string>('/')
    useEffect(() => {
        const active = window.location.pathname
        active && setActive(active)
    }, [])
    return (
        <>
            <Head>
                <title>阿sir's Book</title>
                <meta content="width=device-width, initial-scale=1" name="viewport" />
                <meta name="description" content="Generated by gzq" />
                <link rel="icon" href="/favicon.svg" />
            </Head>
            <div className={cn('h-[4rem] flex items-center justify-between px-6 bg-head')}>
                <div className={cn(s.logo, 'cursor-pointer')}>
                    {
                        title.split('').map((el, index) => {
                            return (
                                <span key={index} className={cn(s[`sp${index + 1}`])}>{el}</span>
                            )
                        })
                    }
                </div>
                <div className="h-full">
                    {
                        menu.map((item, index) => {
                            return (
                                <Link href={item.path} key={index}>
                                    <button
                                        className={cn("inline-block px-2 mx-2 cursor-pointer h-full leading-[4rem] bg-transparent", { 'border-b-2 border-theme text-theme': item.path === active }, { 'text-white': item.path !== active })}
                                    >{item.title}</button>
                                </Link>
                            )
                        })
                    }
                </div>
            </div>
        </>
    )
}